-- schema.sql
-- PostgreSQL
-- Схема БД для партнеров, товаров и истории отгрузок.

BEGIN;

-- Удаляем таблицы в порядке, обратном зависимостям.
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    partner_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name  VARCHAR(150) NOT NULL,
    inn           VARCHAR(12) NOT NULL UNIQUE,
    contact_email VARCHAR(120) NOT NULL UNIQUE,
    phone         VARCHAR(20),
    rating        DECIMAL(2,1),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_partners_company_name
        CHECK (BTRIM(company_name) <> ''),

    CONSTRAINT chk_partners_inn
        CHECK (BTRIM(inn) <> ''),

    CONSTRAINT chk_partners_email
        CHECK (contact_email LIKE '%_@_%._%'),

    CONSTRAINT chk_partners_rating
        CHECK (rating IS NULL OR rating BETWEEN 0 AND 5)
);

CREATE TABLE products (
    product_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL UNIQUE,

    CONSTRAINT chk_products_name
        CHECK (BTRIM(product_name) <> '')
);

CREATE TABLE deliveries (
    delivery_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id    INTEGER NOT NULL,
    product_id    INTEGER NOT NULL,
    delivery_date DATE NOT NULL,
    quantity      INTEGER NOT NULL,
    unit_price    DECIMAL(12,4) NOT NULL,

    CONSTRAINT fk_deliveries_partner
        FOREIGN KEY (partner_id)
        REFERENCES partners(partner_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_deliveries_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_deliveries_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_deliveries_unit_price
        CHECK (unit_price >= 0)
);

-- Индексы для типовых backend-запросов.
CREATE INDEX idx_deliveries_partner_id
    ON deliveries(partner_id);

CREATE INDEX idx_deliveries_partner_date
    ON deliveries(partner_id, delivery_date DESC);

CREATE INDEX idx_deliveries_product_id
    ON deliveries(product_id);

COMMIT;
